version: '3'
services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
#      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master


  api:
    container_name: SpotBot_Api
    build: .
    ports:
      - "5000:5000"
    volumes:
      - $PWD/APPLow/data:/app/data
    environment:
      - APP_ENV=${APP_ENV}
      - CLIENT_ID=$Client_Secret
      - CLIENT_SECRET=$Client_Id
      - NUM_TOKENS=1
    depends_on:
      - redis

  api-worker:
    container_name: SpotBot_worker
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - redis

#  api-beat:
#    build: .
#    command: celery -A tasks.celery beat --loglevel=info
#    environment:
#      - APP_ENV=${APP_ENV}
#    depends_on:
#      - redis